// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: vuztotnvfjqfmcjthtqt

class SupabaseConfig {
  static const String supabaseUrl = 'https://vuztotnvfjqfmcjthtqt.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1enRvdG52ZmpxZm1janRodHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwODQ0MzIsImV4cCI6MjA3OTY2MDQzMn0.hl7j78XkZjp1tWRaHKcdmAUoxTqZNCP6t2thMfGa8nc';
}
